name: elk # Name of the Catalog Entry
description: |
  ELK Stack # Description of the Catalog Entry
version: 1 # Version of the Catalog to be used
category: monitoring # Category to be used for searching catalog entries