.catalog:
  name: "ELK Stack"
  version: "1.0"
  description: "ELK Stack"
  uuid: elk-stack-1
  minimum_rancher_version: v0.51.0

jhipster-elasticsearch:
  scale: 1

jhipster-logstash:
  scale: 1

jhipster-console:
  scale: 1    